#!/usr/bin/python3
"""In-game controller settings OSD for ROCKNIX/Retroid devices."""

import argparse
import fcntl
import glob
import json
import os
import select
import signal
import struct
import subprocess
import time

EV_SYN, EV_KEY, EV_ABS = 0, 1, 3
SYN_REPORT = 0
KEY_ESC, KEY_ENTER, KEY_UP, KEY_DOWN, KEY_F1 = 1, 28, 103, 108, 59
BTN_SOUTH, BTN_EAST, BTN_MODE = 304, 305, 316
ABS_HAT0Y = 17
BUS_USB = 3
UI_DEV_CREATE, UI_DEV_DESTROY = 0x5501, 0x5502
EVENT = struct.Struct("llHHi")


def ioc(direction, kind, number, size):
    return (direction << 30) | (size << 16) | (ord(kind) << 8) | number


def iow(kind, number):
    return ioc(1, kind, number, struct.calcsize("i"))


EVIOCGRAB = iow("E", 0x90)
UI_SET_EVBIT = iow("U", 100)
UI_SET_KEYBIT = iow("U", 101)


class VirtualKeyboard:
    def __init__(self):
        self.fd = os.open("/dev/uinput", os.O_RDWR | os.O_NONBLOCK)
        fcntl.ioctl(self.fd, UI_SET_EVBIT, EV_KEY)
        for code in (KEY_ESC, KEY_ENTER, KEY_UP, KEY_DOWN):
            fcntl.ioctl(self.fd, UI_SET_KEYBIT, code)
        desc = struct.pack(
            "80sHHHHI" + "i" * 256,
            b"Retroid Controls OSD Keyboard", BUS_USB, 0x1209, 0x5250, 1, 0,
            *([0] * 256),
        )
        os.write(self.fd, desc)
        fcntl.ioctl(self.fd, UI_DEV_CREATE)
        time.sleep(0.15)

    def tap(self, code):
        now = time.time()
        sec, usec = int(now), int((now % 1) * 1_000_000)
        for event_type, event_code, value in (
            (EV_KEY, code, 1), (EV_SYN, SYN_REPORT, 0),
            (EV_KEY, code, 0), (EV_SYN, SYN_REPORT, 0),
        ):
            os.write(self.fd, EVENT.pack(sec, usec, event_type, event_code, value))

    def close(self):
        try:
            fcntl.ioctl(self.fd, UI_DEV_DESTROY)
        finally:
            os.close(self.fd)


class OSD:
    BUTTONS = ("a", "b", "x", "y", "l1", "l2", "r1", "r2")
    LABEL = {"a": "A", "b": "B", "x": "X", "y": "Y", "l1": "L1", "l2": "L2", "r1": "R1", "r2": "R2"}
    SETTING = {key: value + "ボタン設定" for key, value in LABEL.items()}

    def __init__(self, context_path):
        self.context_path = context_path
        with open(context_path, encoding="utf-8") as handle:
            self.context = json.load(handle)
        self.settings = self.context.setdefault("settings", {})
        self.fds = []
        self.states = {"home": False, "back": False}
        self.combo_since = None
        self.combo_fired = False
        self.requested = False
        self.running = True
        self.keyboard = VirtualKeyboard()
        self.open_inputs()
        with open("/tmp/retroid-game-osd.pid", "w") as handle:
            handle.write(str(os.getpid()))

    def open_inputs(self):
        # Read only the keyboard generated by the temporary OSD profile. The
        # virtual gamepad may still be producing TURBO/REPEAT output from the
        # game profile, which must never drive the menu.
        wanted = {"InputPlumber Keyboard"}
        for name_path in glob.glob("/sys/class/input/event*/device/name"):
            try:
                with open(name_path, encoding="utf-8") as handle:
                    name = handle.read().strip()
                if name not in wanted:
                    continue
                event = name_path.split("/")[-3]
                fd = os.open("/dev/input/" + event, os.O_RDONLY | os.O_NONBLOCK)
                self.fds.append(fd)
            except OSError:
                pass
        if not self.fds:
            raise RuntimeError("gamepad input devices were not found")

    def drop_fd(self, fd):
        try:
            self.fds.remove(fd)
            os.close(fd)
        except (ValueError, OSError):
            pass

    def ensure_inputs(self):
        if self.fds:
            return
        while self.running and not self.fds:
            try:
                self.open_inputs()
            except RuntimeError:
                time.sleep(0.2)

    def save(self, name, value):
        key = f'{self.context["platform"]}["{self.context["rom_name"]}"].{name}'
        subprocess.run(
            ["/bin/bash", "-c", '. /etc/profile; set_setting "$1" "$2"', "osd", key, value or "default"],
            check=False,
        )
        if value:
            self.settings[name] = value
        else:
            self.settings.pop(name, None)
        self.write_context()
        self.reload_native_profile(load=False)

    def write_context(self):
        temporary = self.context_path + ".new"
        with open(temporary, "w", encoding="utf-8") as handle:
            json.dump(self.context, handle, ensure_ascii=False)
        os.replace(temporary, self.context_path)

    def reload_native_profile(self, load=True):
        try:
            buttons = {}
            for button in self.BUTTONS:
                buttons[button] = self.settings.get(self.SETTING[button], "normal:" + button)
            turbo = {"slow": 6, "fast": 15, "max": 30}.get(self.settings.get("TURBO速度"), 10)
            repeat = {"slow": 6, "fast": 15, "max": 30}.get(self.settings.get("REPEAT速度"), 10)
            delay = {"short": 0.25, "long": 0.70}.get(self.settings.get("REPEAT開始待ち"), 0.45)
            config = {
                "buttons": buttons,
                "direction_mode": self.settings.get("方向入力モード", "8way"),
                "stick_mode": self.settings.get("左スティック入力", "native"),
                "turbo_hz": turbo,
                "repeat_delay": delay,
                "repeat_hz": repeat,
            }
            config_path = self.context.get("config_file", "/tmp/retroid-gamepad-controls.json")
            profile_path = self.context.get("profile_file", "/tmp/retroid-gamepad-profile.yaml")
            temporary = config_path + ".new"
            with open(temporary, "w", encoding="utf-8") as handle:
                json.dump(config, handle)
            os.replace(temporary, config_path)
            generated = subprocess.run(
                ["/storage/.config/input-controls/generate-inputplumber-profile.py",
                 "--config", config_path, "--output", profile_path],
                check=False,
            )
            if generated.returncode != 0:
                return False
            if not load:
                return True
            loaded = subprocess.run(
                ["inputplumber", "device", self.context["gamepad_id"],
                 "profile", "load", profile_path],
                check=False,
            )
            return loaded.returncode == 0
        except (OSError, ValueError):
            return False

    def grab(self, enabled):
        for fd in self.fds:
            try:
                fcntl.ioctl(fd, EVIOCGRAB, int(enabled))
            except OSError:
                pass

    def pump_menu(self, process):
        while process.poll() is None and self.running:
            ready, _, _ = select.select(self.fds, [], [], 0.1)
            for fd in ready:
                try:
                    data = os.read(fd, EVENT.size * 64)
                except BlockingIOError:
                    continue
                except OSError:
                    self.drop_fd(fd)
                    continue
                for offset in range(0, len(data) - EVENT.size + 1, EVENT.size):
                    _, _, kind, code, value = EVENT.unpack_from(data, offset)
                    if kind == EV_ABS and code == ABS_HAT0Y and value:
                        self.keyboard.tap(KEY_UP if value < 0 else KEY_DOWN)
                    elif kind == EV_KEY and value == 1:
                        # Depending on the active native profile, InputPlumber
                        # exposes either gamepad buttons or keyboard keys here.
                        # Re-emit both forms through the dedicated OSD keyboard
                        # so bemenu remains controllable even while RetroArch
                        # owns the normal virtual devices.
                        if code in (KEY_UP, KEY_DOWN, KEY_ENTER, KEY_ESC):
                            self.keyboard.tap(code)
                        elif code == BTN_EAST:
                            self.keyboard.tap(KEY_ENTER)
                        elif code == BTN_SOUTH:
                            self.keyboard.tap(KEY_ESC)

    @staticmethod
    def focused_was_fullscreen():
        """Return whether the currently focused Sway view is fullscreen."""
        try:
            result = subprocess.run(
                ["swaymsg", "-r", "-t", "get_tree"],
                stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
                text=True, check=False,
            )
            tree = json.loads(result.stdout)

            def find_focused(node):
                if node.get("focused"):
                    return node
                for child in node.get("nodes", []) + node.get("floating_nodes", []):
                    found = find_focused(child)
                    if found is not None:
                        return found
                return None

            focused = find_focused(tree)
            return bool(focused and focused.get("fullscreen_mode"))
        except (OSError, ValueError, TypeError):
            return False

    @staticmethod
    def set_fullscreen(enabled):
        subprocess.run(
            ["swaymsg", "fullscreen", "enable" if enabled else "disable"],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=False,
        )

    def choose(self, title, choices):
        labels = [label for label, _ in choices]
        env = os.environ.copy()
        env["BEMENU_BACKEND"] = "wayland"
        command = [
            "bemenu", "-f", "-c", "-l", str(min(12, len(labels))), "-H", "48", "-W", "0.88",
            "-p", title, "--fn", "DejaVu Sans 18",
            "--tb", "#20242b", "--tf", "#ffffff", "--fb", "#16191e",
            "--ff", "#dddddd", "--nb", "#16191e", "--nf", "#dddddd",
            "--hb", "#b02020", "--hf", "#ffffff",
        ]
        process = subprocess.Popen(
            command, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
            text=True, env=env,
        )
        process.stdin.write("\n".join(labels) + "\n")
        process.stdin.close()
        # The temporary InputPlumber profile turns the D-pad/A/B into keyboard
        # arrows/Enter/Esc, so bemenu can receive them even when the emulator
        # owns the virtual gamepad exclusively.
        self.pump_menu(process)
        output = process.stdout.read().strip() if process.stdout else ""
        for label, value in choices:
            if output == label:
                return value
        return None

    @staticmethod
    def shown(value, defaults):
        return defaults.get(value, value) if value else "Default"

    def mapping_menu(self, button):
        name = self.SETTING[button]
        current = self.settings.get(name, "")
        choices = [("Default", "")]
        for mode, mode_label in (("normal", "NORMAL"), ("turbo", "TURBO"), ("repeat", "REPEAT"), ("toggle", "TOGGLE")):
            for target in self.BUTTONS:
                choices.append((f"{mode_label} → {self.LABEL[target]}", f"{mode}:{target}"))
            choices.append((f"{mode_label} -> ALL", f"{mode}:all"))
        choices.insert(1, ("Disabled", "normal:off"))
        selected = self.choose(f"{self.LABEL[button]} Mapping [{current or 'Default'}]", choices)
        if selected is not None:
            self.save(name, selected)

    def main_menu(self):
        while self.running:
            entries = []
            for button in self.BUTTONS:
                name = self.SETTING[button]
                entries.append((f"{self.LABEL[button]}: {self.settings.get(name) or 'Default'}", "button:" + button))
            entries += [
                (f"D-pad Mode: {self.settings.get('方向入力モード') or 'Default'}", "direction"),
                (f"Left Stick: {self.settings.get('左スティック入力') or 'Default'}", "stick"),
                (f"TURBO Rate: {self.settings.get('TURBO速度') or 'Default'}", "turbo"),
                (f"REPEAT Delay: {self.settings.get('REPEAT開始待ち') or 'Default'}", "repeat_delay"),
                (f"REPEAT Rate: {self.settings.get('REPEAT速度') or 'Default'}", "repeat_speed"),
            ]
            if self.context.get("platform") == "arcade":
                entries += [
                    (f"Touch Mode: {self.settings.get('タッチ操作モード') or 'Default'}", "touch"),
                    (f"Mouse Speed: {self.settings.get('マウス移動量') or 'Default'}%", "movement"),
                    (f"Trackball Inertia: {self.settings.get('トラックボール慣性速度') or 'Default'}", "inertia"),
                ]
            entries.append(("Close", "close"))
            action = self.choose("RETROID CONTROLS  A:Select / B:Back", entries)
            if action is None or action == "close":
                return
            if action.startswith("button:"):
                self.mapping_menu(action.split(":", 1)[1])
                continue
            menus = {
                "direction": ("D-pad Mode", [("Default", ""), ("8-way", "8way"), ("4-way", "4way")]),
                "stick": ("Left Stick", [("Default", ""), ("Analog", "native"), ("D-pad", "dpad")]),
                "turbo": ("TURBO Rate", [("Default", ""), ("Slow 6Hz", "slow"), ("Normal 10Hz", "normal"), ("Fast 15Hz", "fast"), ("Maximum 30Hz", "max")]),
                "repeat_delay": ("REPEAT Delay", [("Default", ""), ("Short", "short"), ("Normal", "normal"), ("Long", "long")]),
                "repeat_speed": ("REPEAT Rate", [("Default", ""), ("Slow 6Hz", "slow"), ("Normal 10Hz", "normal"), ("Fast 15Hz", "fast"), ("Maximum 30Hz", "max")]),
                "touch": ("Touch Mode", [("Default", ""), ("Touchscreen", "touch"), ("Mouse", "mouse"), ("Trackball", "trackball")]),
                "movement": ("Mouse Speed", [("Default", "")] + [(f"{n}%", str(n)) for n in range(10, 201, 10)]),
                "inertia": ("Trackball Inertia", [("Default", "")] + [(f"{n}%", str(n)) for n in range(10, 201, 10)]),
            }
            name, choices = menus[action]
            selected = self.choose(name, choices)
            if selected is not None:
                self.save(name, selected)

    def open_menu(self):
        previous = "/tmp/retroid-osd-previous-profile.yaml"
        profile = "/storage/.config/input-controls/retroid-osd-profile.yaml"
        loaded = False
        was_fullscreen = self.focused_was_fullscreen()
        try:
            # ROCKNIX enables tearing for the fullscreen emulator surface. On
            # RP5 that surface is composited above bemenu's layer-shell view,
            # so briefly leave fullscreen while the OSD is visible.
            if was_fullscreen:
                self.set_fullscreen(False)
            result = subprocess.run(
                ["inputplumber", "device", self.context["gamepad_id"], "profile", "dump"],
                stdout=subprocess.PIPE, text=True, check=False,
            )
            if result.returncode == 0 and result.stdout:
                with open(previous, "w", encoding="utf-8") as handle:
                    handle.write(result.stdout)
                loaded = subprocess.run(
                    ["inputplumber", "device", self.context["gamepad_id"],
                     "profile", "load", profile],
                    check=False,
                ).returncode == 0
            self.main_menu()
        finally:
            if loaded:
                # Rebuild from the possibly edited settings. Falling back to
                # the saved profile prevents leaving OSD keyboard mappings on.
                if not self.reload_native_profile():
                    subprocess.run(
                        ["inputplumber", "device", self.context["gamepad_id"],
                         "profile", "load", previous],
                        check=False,
                    )
            try:
                os.unlink(previous)
            except OSError:
                pass
            if was_fullscreen:
                self.set_fullscreen(True)

    def handle_event(self, kind, code, value):
        if kind != EV_KEY:
            return
        if code == BTN_MODE:
            self.states["home"] = bool(value)
        elif code == KEY_F1:
            self.states["back"] = bool(value)

    def run(self):
        while self.running:
            if self.requested:
                self.requested = False
                self.grab(True)
                try:
                    self.open_menu()
                finally:
                    self.grab(False)
                continue
            self.ensure_inputs()
            ready, _, _ = select.select(self.fds, [], [], 0.05)
            for fd in ready:
                try:
                    data = os.read(fd, EVENT.size * 64)
                except BlockingIOError:
                    continue
                except OSError:
                    self.drop_fd(fd)
                    self.states = {"home": False, "back": False}
                    self.combo_since = None
                    continue
                for offset in range(0, len(data) - EVENT.size + 1, EVENT.size):
                    _, _, kind, code, value = EVENT.unpack_from(data, offset)
                    self.handle_event(kind, code, value)
            both = self.states["home"] and self.states["back"]
            if both and self.combo_since is None:
                self.combo_since = time.monotonic()
            if both and self.combo_since and time.monotonic() - self.combo_since >= 0.65:
                self.combo_fired = True
            if not both:
                self.combo_since = None
            # Wait until both keys are released so the emulator cannot retain a
            # grabbed key-down state while the menu is open.
            if self.combo_fired and not self.states["home"] and not self.states["back"]:
                self.combo_fired = False
                self.grab(True)
                try:
                    self.open_menu()
                finally:
                    self.grab(False)

    def stop(self, *_):
        self.running = False

    def request_menu(self, *_):
        self.requested = True

    def close(self):
        self.grab(False)
        for fd in self.fds:
            os.close(fd)
        self.keyboard.close()
        try:
            if open("/tmp/retroid-game-osd.pid").read().strip() == str(os.getpid()):
                os.unlink("/tmp/retroid-game-osd.pid")
        except OSError:
            pass


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--context", required=True)
    args = parser.parse_args()
    osd = OSD(args.context)
    signal.signal(signal.SIGTERM, osd.stop)
    signal.signal(signal.SIGINT, osd.stop)
    signal.signal(signal.SIGUSR1, osd.request_menu)
    try:
        osd.run()
    finally:
        osd.close()


if __name__ == "__main__":
    main()
